NEWS_DATA = {'status': 'ok', 'totalResults': 25,
             'articles': [
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Is Tesla, Inc. (TSLA) The Best EV Stock to Buy According to Billionaires?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_da1dfd40-72c1-41d5-a0a6-b896b5be1ba0',
     'urlToImage': None, 'publishedAt': '2025-03-10T19:52:03Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Jim Cramer Says Tesla, Inc. (TSLA) Has Been ‘Dependent On This Data Center And The Spend’',
     'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_53745697-1fea-4b77-882d-22e29d4a3f5b',
     'urlToImage': None, 'publishedAt': '2025-02-27T11:20:06Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Is Tesla, Inc. (TSLA) the Best Growth Stock to Invest in for the Next 10 Years?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_c1e70a11-4055-4e90-89a3-23f28dff82c8',
     'urlToImage': None, 'publishedAt': '2025-03-16T14:12:41Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Tesla, Inc.\xa0(TSLA) Faces Challenges as Price Target Cut to $320 Amid Weak Demand',
     'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_42ba804c-4af1-48ff-a510-dd0c72c98e65',
     'urlToImage': None, 'publishedAt': '2025-03-06T08:38:12Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Tesla, Inc. (TSLA): Among The Stocks With At Least $20 Million In Insider Sales Recently',
     'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_2433f22a-38ea-42ea-8ec6-7d9ea7a03935',
     'urlToImage': None, 'publishedAt': '2025-03-10T01:41:06Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Tesla, Inc. (TSLA): ‘Republicans Go Crazy for Him!’ Jim Cramer on Elon Musk’s Impact',
     'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_bcc53162-7ee2-43be-ac80-495d97912469',
     'urlToImage': None, 'publishedAt': '2025-03-11T17:22:38Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+702 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Jabran Kundi',
     'title': 'Tesla, Inc. (TSLA): A High Growth Mega Cap Stock You Can Buy and Hold for the Next 5 Years',
     'description': 'We recently compiled a list of the 20 High Growth Mega Cap Stocks You Can Buy And Hold For Next 5 Years. In this article, we are going to take a look at...',
     'url': 'https://finance.yahoo.com/news/tesla-inc-tsla-high-growth-005814330.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/R3DsTXHuX1Up50du0B.awA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/1277c6032fd09b727a10249a170024cf',
     'publishedAt': '2025-02-25T00:58:14Z',
     'content': 'We recently compiled a list of the 20 High Growth Mega Cap Stocks You Can Buy And Hold For Next 5 Years.\xa0In this article, we are going to take a look at where Tesla, Inc. (NASDAQ:TSLA) stands against… [+3313 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Insider Monkey',
     'title': 'TD Cowen Upgrades Tesla, Inc.\xa0(TSLA) to Buy, Citing Recent Pullback and Upcoming Catalysts',
     'description': 'We recently compiled a list of the 10 AI Stocks Trending On Wall Street Right Now. In this article, we are going to take a look at where Tesla, Inc. (NASDAQ:TSLA) stands against the other AI stocks. Determined to lead the AI frontier, China is deploying every…',
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_d198742e-1fc9-493e-93fe-3ff17993b955',
     'urlToImage': None, 'publishedAt': '2025-03-12T15:12:33Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+703 chars]"},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Valmark Advisers Inc. Boosts Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Valmark Advisers Inc. boosted its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 11.3% during the fourth quarter, according to the company in its most recent Form 13F filing with the SEC. The institutional investor owned 16,451 shares of the…',
     'url': 'https://www.etfdailynews.com/2025/02/20/valmark-advisers-inc-boosts-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:51Z',
     'content': 'Valmark Advisers Inc. boosted its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 11.3% during the fourth quarter, according to the company in its most recent Form 13F filing with th… [+5356 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Lee Financial Co Boosts Stock Holdings in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Lee Financial Co increased its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 14.5% in the 4th quarter, according to its most recent disclosure with the Securities & Exchange Commission. The institutional investor owned 1,421 shares of the e…',
     'url': 'https://www.etfdailynews.com/2025/02/20/lee-financial-co-boosts-stock-holdings-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:55Z',
     'content': 'Lee Financial Co increased its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 14.5% in the 4th quarter, according to its most recent disclosure with the Securities &amp; Exchange Co… [+5823 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Rep. Julie Johnson Sells Off Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Representative Julie Johnson (D-Texas) recently sold shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 12th, the Representative disclosed that they had sold between $15,001 and $50,000 in Tesla stock on February 12th. The trade occurred in t…',
     'url': 'https://www.etfdailynews.com/2025/03/14/rep-julie-johnson-sells-off-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-14T06:36:43Z',
     'content': 'Representative Julie Johnson (D-Texas) recently sold shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 12th, the Representative disclosed that they had sold between $15,001 and $50,… [+6970 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'AlphaQuest LLC Has $78,000 Stock Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'AlphaQuest LLC lessened its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 97.9% in the fourth quarter, according to its most recent filing with the SEC. The firm owned 193 shares of the electric vehicle producer’s stock after selling 8,837 …',
     'url': 'https://www.etfdailynews.com/2025/03/20/alphaquest-llc-has-78000-stock-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-20T08:42:49Z',
     'content': 'AlphaQuest LLC lessened its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 97.9% in the fourth quarter, according to its most recent filing with the SEC. The firm owned 193 shares o… [+6019 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Allworth Financial LP Increases Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Allworth Financial LP lifted its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 13.6% in the 4th quarter, according to the company in its most recent 13F filing with the Securities & Exchange Commission. The institutional investor owned 72,196 shares …',
     'url': 'https://www.etfdailynews.com/2025/02/20/allworth-financial-lp-increases-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T12:24:49Z',
     'content': 'Allworth Financial LP lifted its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 13.6% in the 4th quarter, according to the company in its most recent 13F filing with the Securities &amp; Exch… [+6248 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Receives $318.77 Consensus Target Price from Brokerages',
     'description': 'Shares of Tesla, Inc. (NASDAQ:TSLA – Get Free Report) have earned a consensus recommendation of “Hold” from the thirty-seven brokerages that are currently covering the stock, MarketBeat Ratings reports. Eight analysts have rated the stock with a sell rating, …',
     'url': 'https://www.etfdailynews.com/2025/03/09/tesla-inc-nasdaqtsla-receives-318-77-consensus-target-price-from-brokerages/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-09T15:14:44Z',
     'content': 'Shares of Tesla, Inc. (NASDAQ:TSLA – Get Free Report) have earned a consensus recommendation of “Hold” from the thirty-seven brokerages that are currently covering the stock, MarketBeat Ratings repor… [+5500 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Csenge Advisory Group Decreases Stock Holdings in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Csenge Advisory Group decreased its holdings in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 5.9% during the fourth quarter, according to its most recent filing with the Securities and Exchange Commission (SEC). The institutional investor owned 22,804…',
     'url': 'https://www.etfdailynews.com/2025/02/20/csenge-advisory-group-decreases-stock-holdings-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:50Z',
     'content': 'Csenge Advisory Group decreased its holdings in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 5.9% during the fourth quarter, according to its most recent filing with the Securities and Exchan… [+6064 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'L.M. Kohn & Company Reduces Holdings in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'L.M. Kohn & Company cut its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.5% in the 4th quarter, according to its most recent filing with the Securities and Exchange Commission (SEC). The firm owned 5,167 shares of the electric vehicle produ…',
     'url': 'https://www.etfdailynews.com/2025/02/20/l-m-kohn-company-reduces-holdings-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:52Z',
     'content': 'L.M. Kohn &amp; Company cut its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.5% in the 4th quarter, according to its most recent filing with the Securities and Exchange Commission … [+6165 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Rep. Marjorie Taylor Greene Purchases Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Representative Marjorie Taylor Greene (R-Georgia) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 09th, the Representative disclosed that they had bought between $1,001 and $15,000 in Tesla stock on March 7th. Representativ…',
     'url': 'https://www.etfdailynews.com/2025/03/12/rep-marjorie-taylor-greene-purchases-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-12T07:08:50Z',
     'content': 'Representative Marjorie Taylor Greene (R-Georgia) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 09th, the Representative disclosed that they had bought between $… [+7007 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Rep. Julie Johnson Sells Tesla, Inc. (NASDAQ:TSLA) Stock',
     'description': 'Representative Julie Johnson (D-Texas) recently sold shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 12th, the Representative disclosed that they had sold between $1,001 and $15,000 in Tesla stock on February 11th. The trade occurred in th…',
     'url': 'https://www.etfdailynews.com/2025/03/15/rep-julie-johnson-sells-tesla-inc-nasdaqtsla-stock/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-15T07:11:16Z',
     'content': 'Representative Julie Johnson (D-Texas) recently sold shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 12th, the Representative disclosed that they had sold between $1,001 and $15,0… [+6999 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Rep. Gilbert Ray Cisneros, Jr. Purchases Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Representative Gilbert Ray Cisneros, Jr. (D-California) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 06th, the Representative disclosed that they had bought between $1,001 and $15,000 in Tesla stock on February 26th. The…',
     'url': 'https://www.etfdailynews.com/2025/03/08/rep-gilbert-ray-cisneros-jr-purchases-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-03-08T07:36:48Z',
     'content': 'Representative Gilbert Ray Cisneros, Jr. (D-California) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on March 06th, the Representative disclosed that they had bought bet… [+7467 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'MN Wealth Advisors LLC Buys 80 Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'MN Wealth Advisors LLC lifted its stake in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 7.1% during the 4th quarter, according to its most recent disclosure with the Securities & Exchange Commission. The firm owned 1,203 shares of the electric vehicle producer’…',
     'url': 'https://www.etfdailynews.com/2025/02/20/mn-wealth-advisors-llc-buys-80-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:53Z',
     'content': 'MN Wealth Advisors LLC lifted its stake in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 7.1% during the 4th quarter, according to its most recent disclosure with the Securities &amp; Exchange Commissio… [+5543 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Stanich Group LLC Makes New $312,000 Investment in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Stanich Group LLC purchased a new position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) during the 4th quarter, according to its most recent Form 13F filing with the SEC. The fund purchased 773 shares of the electric vehicle producer’s stock, valued a…',
     'url': 'https://www.etfdailynews.com/2025/02/20/stanich-group-llc-makes-new-312000-investment-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:55Z',
     'content': 'Stanich Group LLC purchased a new position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) during the 4th quarter, according to its most recent Form 13F filing with the SEC. The fund purchased 7… [+6094 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Blue Zone Wealth Advisors LLC Has $3.01 Million Stock Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Blue Zone Wealth Advisors LLC reduced its holdings in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1.2% in the fourth quarter, according to its most recent Form 13F filing with the Securities and Exchange Commission (SEC). The fund owned 7,443 shares …',
     'url': 'https://www.etfdailynews.com/2025/02/20/blue-zone-wealth-advisors-llc-has-3-01-million-stock-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:54Z',
     'content': 'Blue Zone Wealth Advisors LLC reduced its holdings in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1.2% in the fourth quarter, according to its most recent Form 13F filing with the Securities… [+6234 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Shares Sold by Sheaff Brock Investment Advisors LLC',
     'description': 'Sheaff Brock Investment Advisors LLC reduced its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.4% during the 4th quarter, according to the company in its most recent filing with the Securities and Exchange Commission (SEC). The fund owned 25…',
     'url': 'https://www.etfdailynews.com/2025/02/20/tesla-inc-nasdaqtsla-shares-sold-by-sheaff-brock-investment-advisors-llc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-02-20T09:40:52Z',
     'content': 'Sheaff Brock Investment Advisors LLC reduced its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.4% during the 4th quarter, according to the company in its most recent filing with the… [+5587 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Michael Saylor's Strategy Inc Along With CrowdStrike, Best Buy, Credo Technology, And Tesla: Why Are These 5 Stocks On Investors' Radars Today",
     'description': 'U.S. stocks slid on Tuesday as President Donald Trump’s tariffs on major trade partners took effect, intensifying global trade tensions. The Dow Jones Industrial Average dropped 1.55% to 42,520.99, while the S&P 500 declined 1.22% to 5,778.15. The Nasdaq Comp…',
     'url': 'https://biztoc.com/x/65b87cbc75c2afc7', 'urlToImage': 'https://biztoc.com/cdn/65b87cbc75c2afc7_s.webp',
     'publishedAt': '2025-03-05T00:34:28Z',
     'content': 'U.S. stocks slid on Tuesday as President Donald Trumps tariffs on major trade partners took effect, intensifying global trade tensions. The Dow Jones Industrial Average dropped 1.55% to 42,520.99, wh… [+142 chars]'},
    {'source': {'id': None, 'name': 'Freerepublic.com'}, 'author': 'San Antonio Express News',
     'title': "Musk's cost-cutting DOGE lays off workers at agency that oversees Tesla Inc.",
     'description': 'Elon Musk’s cost-cutting team is eliminating jobs at the vehicle safety agency that oversees his Tesla Inc., regulates the autonomous vehicles he says represents its future and has launched investigations into deadly crashes involving the Texas-based company’…',
     'url': 'https://freerepublic.com/focus/f-chat/4299920/posts', 'urlToImage': None,
     'publishedAt': '2025-02-23T21:38:19Z',
     'content': "Skip to comments.\r\nMusk's cost-cutting DOGE lays off workers at agency that oversees Tesla Inc.San Antonio Express News ^\r\n | 02/22/2025\r\n | By Staff and Wire Reports\r\nPosted on 02/23/2025 1:38:19 PM… [+4720 chars]"}]}
